In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,5,3]],columns=('A','B','C'))
df.head()

   A  B  C
0  1  2  3
1  4  5  6
2  7  5  3

In [19]:
df = pd.read_csv('ds/coffee.csv')

In [5]:
bios = pd.read_csv('ds/bios.csv')

In [6]:
olympics_data = pd.read_excel('ds/olympics-data.xlsx')
noc_regions = pd.read_csv('ds/noc_regions.csv')
results = pd.read_csv('ds/results.csv')

In [7]:
df.loc[0]

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [13]:
df

          Day Coffee Type  Units Sold
1      Monday       Latte          15
11   Saturday       Latte          35
8      Friday    Espresso          45
13     Sunday       Latte          35
7    Thursday       Latte          30
4   Wednesday    Espresso          35
9      Friday       Latte          35
6    Thursday    Espresso          40
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
0      Monday    Espresso          25
10   Saturday    Espresso          45
12     Sunday    Espresso          45
5   Wednesday       Latte          25

In [18]:
df.iloc[0,1]

'Latte'

In [8]:
df = df.sample(frac=1)

In [9]:
df.loc[0,'Day']

'Monday'

In [10]:
df.iloc[0,[2]]

Units Sold    15
Name: 1, dtype: object

In [48]:
df.loc[1,['Units Sold']] = 10

In [57]:
df.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          10
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [56]:
df = df.drop(columns='Units sold')

In [ ]:
df.sort_values(['Units Sold','Coffee Type'])

          Day Coffee Type  Units Sold
1      Monday       Latte          10
3     Tuesday       Latte          20
0      Monday    Espresso          25
5   Wednesday       Latte          25
2     Tuesday    Espresso          30
7    Thursday       Latte          30
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45

In [66]:
bios.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  object
 2   born_date     143693 non-null  object
 3   born_city     110908 non-null  object
 4   born_region   110908 non-null  object
 5   born_country  110908 non-null  object
 6   NOC           145499 non-null  object
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 11.1+ MB

In [28]:
bios.loc[(bios['height_cm']>215) & (bios['born_city'] == 'Newark'),['name','born_city','height_cm']]

                  name born_city  height_cm
6722  Shaquille O'Neal    Newark      216.0

In [72]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [78]:
bios.loc[(bios['height_cm']>215) & (bios['born_country']== 'USA'),['name','height_cm','born_country']]

                    name  height_cm born_country
5781      Tommy Burleson      223.0          USA
6722    Shaquille O'Neal      216.0          USA
6937      David Robinson      216.0          USA
123850    Tyson Chandler      216.0          USA

In [5]:
df.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [10]:
df.loc[2,'Units Sold'] = 1

In [11]:
df.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso           1
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [12]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [19]:
bios.loc[bios['height_cm']>200,['name','height_cm']].head(5)

                    name  height_cm
1080      Bozhil Lozanov      208.0
1673    Alexis Rubalcaba      204.0
2647       Milan Šrejber      203.0
2827  Nik'oloz Deriugini      206.0
2832       Elşad Qadaşev      205.0

In [30]:
bios[bios['name'].str.contains('Bozhil')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1080,1087,Bozhil Lozanov,1934-08-16,NaN,NaN,NaN,Bulgaria,208.0,133.0,NaN
9135,9186,Petar Bozhilov,1963-09-05,Sofia,Sofia Grad,BUL,Bulgaria,186.0,78.0,2012-12-16
83610,84272,Vasil Bozhilov,1967-09-18,NaN,NaN,NaN,Bulgaria,NaN,NaN,NaN
91514,92243,Tsvetana Bozhilova,1968-10-19,Pazardzhik,Pazardzhik,BUL,Bulgaria,172.0,98.0,NaN
130310,132987,Georgi Bozhilov,1989-04-09,Sofia,Sofia Grad,BUL,Bulgaria,201.0,107.0,NaN

In [32]:
coffee = pd.read_csv('ds/coffee.csv')

In [33]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [34]:
coffee['price'] = 3.99

In [35]:
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   3.99
1     Monday       Latte          15   3.99
2    Tuesday    Espresso          30   3.99
3    Tuesday       Latte          20   3.99
4  Wednesday    Espresso          35   3.99

In [37]:
coffee.head()

         Day Coffee Type  Units Sold  price  new_price
0     Monday    Espresso          25   3.99       5.99
1     Monday       Latte          15   3.99       3.99
2    Tuesday    Espresso          30   3.99       5.99
3    Tuesday       Latte          20   3.99       3.99
4  Wednesday    Espresso          35   3.99       5.99