In [4]:
import pandas as pd

In [5]:
data = {
    "Name": ["A","B","C"],
    "Sales":[100,200,150]
}

df = pd.DataFrame(data)
df

  Name  Sales
0    A    100
1    B    200
2    C    150

In [6]:
df.to_csv("friends")

In [7]:
data2 = {
    "names":["Mohan","Rohan","Johan","Sohan"],
    "Salary":[90000,80000,70000,90]
}
table = pd.DataFrame(data2)
table

   names  Salary
0  Mohan   90000
1  Rohan   80000
2  Johan   70000
3  Sohan      90

In [8]:
table.to_csv('file1',index=False)

In [9]:
table.describe()

             Salary
count      4.000000
mean   60022.500000
std    40780.739224
min       90.000000
25%    52522.500000
50%    75000.000000
75%    82500.000000
max    90000.000000

In [10]:
table.name("calories")

AttributeError: 'DataFrame' object has no attribute 'name'

In [ ]:
data2.name=("calories")

AttributeError: 'dict' object has no attribute 'name' and no __dict__ for setting new attributes

In [ ]:
data2.name = "calories"

AttributeError: 'dict' object has no attribute 'name' and no __dict__ for setting new attributes

In [ ]:
str = ([1,2,3,5,6,7])
new = pd.Series(str)
new

0    1
1    2
2    3
3    5
4    6
5    7
dtype: int64

In [ ]:
str.name = "numbers"

AttributeError: 'list' object has no attribute 'name' and no __dict__ for setting new attributes

In [11]:
data = {
     "Customer_ID": [101,102,103,104,105,106,107,108],
    "Customer_Name": ["Mohan","Rohan","Sohan","Aman","Karan","Neha","Priya","Rahul"],
    "City": ["Delhi","Mumbai","Delhi","Bangalore","Mumbai","Delhi","Bangalore","Mumbai"],
    "Product": ["Laptop","Phone","Tablet","Laptop","Phone","Tablet","Laptop","Phone"],
    "Sales": [55000,20000,15000,60000,22000,14000,58000,21000],
    "Profit": [8000,3000,2000,9000,3200,1800,8500,3100],
    "Quantity": [2,5,3,1,4,2,2,6],
    "Order_Date": [
        "2024-01-10","2024-01-12","2024-01-15","2024-02-01",
        "2024-02-05","2024-02-10","2024-03-02","2024-03-08"
    ]
}

df = pd.DataFrame(data)
df

,Customer_ID,Customer_Name,City,Product,Sales,Profit,Quantity,Order_Date
0,101,Mohan,Delhi,Laptop,55000,8000,2,2024-01-10
1,102,Rohan,Mumbai,Phone,20000,3000,5,2024-01-12
2,103,Sohan,Delhi,Tablet,15000,2000,3,2024-01-15
3,104,Aman,Bangalore,Laptop,60000,9000,1,2024-02-01
4,105,Karan,Mumbai,Phone,22000,3200,4,2024-02-05
5,106,Neha,Delhi,Tablet,14000,1800,2,2024-02-10
6,107,Priya,Bangalore,Laptop,58000,8500,2,2024-03-02
7,108,Rahul,Mumbai,Phone,21000,3100,6,2024-03-08

In [ ]:
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_ID    8 non-null      int64
 1   Customer_Name  8 non-null      object
 2   City           8 non-null      object
 3   Product        8 non-null      object
 4   Sales          8 non-null      int64
 5   Profit         8 non-null      int64
 6   Quantity       8 non-null      int64
 7   Order_Date     8 non-null      object
dtypes: int64(4), object(4)
memory usage: 644.0+ bytes

       Customer_ID         Sales       Profit  Quantity
count      8.00000      8.000000     8.000000  8.000000
mean     104.50000  33125.000000  4825.000000  3.125000
std        2.44949  20552.632782  3095.965116  1.726888
min      101.00000  14000.000000  1800.000000  1.000000
25%      102.75000  18750.000000  2750.000000  2.000000
50%      104.50000  21500.000000  3150.000000  2.500000
75%      106.25000  55750.000000  8125.000000  4.250000
max      108.00000  60000.000000  9000.000000  6.000000

In [13]:
df["profit_margin"] = df["Sales"] / df["Profit"]

In [14]:
df

,Customer_ID,Customer_Name,City,Product,Sales,Profit,Quantity,Order_Date,profit_margin
0,101,Mohan,Delhi,Laptop,55000,8000,2,2024-01-10,6.875000
1,102,Rohan,Mumbai,Phone,20000,3000,5,2024-01-12,6.666667
2,103,Sohan,Delhi,Tablet,15000,2000,3,2024-01-15,7.500000
3,104,Aman,Bangalore,Laptop,60000,9000,1,2024-02-01,6.666667
4,105,Karan,Mumbai,Phone,22000,3200,4,2024-02-05,6.875000
5,106,Neha,Delhi,Tablet,14000,1800,2,2024-02-10,7.777778
6,107,Priya,Bangalore,Laptop,58000,8500,2,2024-03-02,6.823529
7,108,Rahul,Mumbai,Phone,21000,3100,6,2024-03-08,6.774194

In [15]:
df.rename(columns={"Sales":"Revenue"})

,Customer_ID,Customer_Name,City,Product,Revenue,Profit,Quantity,Order_Date,profit_margin
0,101,Mohan,Delhi,Laptop,55000,8000,2,2024-01-10,6.875000
1,102,Rohan,Mumbai,Phone,20000,3000,5,2024-01-12,6.666667
2,103,Sohan,Delhi,Tablet,15000,2000,3,2024-01-15,7.500000
3,104,Aman,Bangalore,Laptop,60000,9000,1,2024-02-01,6.666667
4,105,Karan,Mumbai,Phone,22000,3200,4,2024-02-05,6.875000
5,106,Neha,Delhi,Tablet,14000,1800,2,2024-02-10,7.777778
6,107,Priya,Bangalore,Laptop,58000,8500,2,2024-03-02,6.823529
7,108,Rahul,Mumbai,Phone,21000,3100,6,2024-03-08,6.774194

In [16]:
df

,Customer_ID,Customer_Name,City,Product,Sales,Profit,Quantity,Order_Date,profit_margin
0,101,Mohan,Delhi,Laptop,55000,8000,2,2024-01-10,6.875000
1,102,Rohan,Mumbai,Phone,20000,3000,5,2024-01-12,6.666667
2,103,Sohan,Delhi,Tablet,15000,2000,3,2024-01-15,7.500000
3,104,Aman,Bangalore,Laptop,60000,9000,1,2024-02-01,6.666667
4,105,Karan,Mumbai,Phone,22000,3200,4,2024-02-05,6.875000
5,106,Neha,Delhi,Tablet,14000,1800,2,2024-02-10,7.777778
6,107,Priya,Bangalore,Laptop,58000,8500,2,2024-03-02,6.823529
7,108,Rahul,Mumbai,Phone,21000,3100,6,2024-03-08,6.774194

In [17]:
df.rename(columns={"Sales":"Revenue"},inplace=True)

In [18]:
df

,Customer_ID,Customer_Name,City,Product,Revenue,Profit,Quantity,Order_Date,profit_margin
0,101,Mohan,Delhi,Laptop,55000,8000,2,2024-01-10,6.875000
1,102,Rohan,Mumbai,Phone,20000,3000,5,2024-01-12,6.666667
2,103,Sohan,Delhi,Tablet,15000,2000,3,2024-01-15,7.500000
3,104,Aman,Bangalore,Laptop,60000,9000,1,2024-02-01,6.666667
4,105,Karan,Mumbai,Phone,22000,3200,4,2024-02-05,6.875000
5,106,Neha,Delhi,Tablet,14000,1800,2,2024-02-10,7.777778
6,107,Priya,Bangalore,Laptop,58000,8500,2,2024-03-02,6.823529
7,108,Rahul,Mumbai,Phone,21000,3100,6,2024-03-08,6.774194

In [19]:
df.describe(
)

       Customer_ID       Revenue       Profit  Quantity  profit_margin
count      8.00000      8.000000     8.000000  8.000000       8.000000
mean     104.50000  33125.000000  4825.000000  3.125000       6.994854
std        2.44949  20552.632782  3095.965116  1.726888       0.412368
min      101.00000  14000.000000  1800.000000  1.000000       6.666667
25%      102.75000  18750.000000  2750.000000  2.000000       6.747312
50%      104.50000  21500.000000  3150.000000  2.500000       6.849265
75%      106.25000  55750.000000  8125.000000  4.250000       7.031250
max      108.00000  60000.000000  9000.000000  6.000000       7.777778

In [20]:
df["new"] = df["sales"]

KeyError: 'sales'

,Customer_ID,Customer_Name,City,Product,Revenue,Profit,Quantity,Order_Date,profit_margin
0,101,Mohan,Delhi,Laptop,55000,8000,2,2024-01-10,6.875000
1,102,Rohan,Mumbai,Phone,20000,3000,5,2024-01-12,6.666667
2,103,Sohan,Delhi,Tablet,15000,2000,3,2024-01-15,7.500000
3,104,Aman,Bangalore,Laptop,60000,9000,1,2024-02-01,6.666667
4,105,Karan,Mumbai,Phone,22000,3200,4,2024-02-05,6.875000
5,106,Neha,Delhi,Tablet,14000,1800,2,2024-02-10,7.777778
6,107,Priya,Bangalore,Laptop,58000,8500,2,2024-03-02,6.823529
7,108,Rahul,Mumbai,Phone,21000,3100,6,2024-03-08,6.774194

In [22]:
df["new"]

KeyError: 'new'

In [72]:
data = {
    "Customer": ["Mohan","Rohan","Sohan","Aman","Neha","Priya","Karan","Rahul"],
    "City": ["Delhi","Mumbai","Delhi","Bangalore","Mumbai","Delhi","Bangalore","Mumbai"],
    "Product": ["Laptop","Phone","Tablet","Laptop","Phone","Tablet","Laptop","Phone"],
    "Sales": [55000,20000,15000,60000,22000,14000,58000,21000],
    "Profit": [8000,3000,2000,9000,3200,1800,8500,None],
    "Quantity": [2,5,3,1,4,2,2,6]
}
df = pd.DataFrame[data]

TypeError: type 'DataFrame' is not subscriptable

In [73]:
dd = pd.DataFrame(data)

In [74]:
dd

  Customer       City Product  Sales  Profit  Quantity
0    Mohan      Delhi  Laptop  55000  8000.0         2
1    Rohan     Mumbai   Phone  20000  3000.0         5
2    Sohan      Delhi  Tablet  15000  2000.0         3
3     Aman  Bangalore  Laptop  60000  9000.0         1
4     Neha     Mumbai   Phone  22000  3200.0         4
5    Priya      Delhi  Tablet  14000  1800.0         2
6    Karan  Bangalore  Laptop  58000  8500.0         2
7    Rahul     Mumbai   Phone  21000     NaN         6

In [27]:
dd.head(5)

  Customer       City Product  Sales  Profit  Quantity
0    Mohan      Delhi  Laptop  55000    8000         2
1    Rohan     Mumbai   Phone  20000    3000         5
2    Sohan      Delhi  Tablet  15000    2000         3
3     Aman  Bangalore  Laptop  60000    9000         1
4     Neha     Mumbai   Phone  22000    3200         4

In [28]:
dd.info

<bound method DataFrame.info of   Customer       City Product  Sales  Profit  Quantity
0    Mohan      Delhi  Laptop  55000    8000         2
1    Rohan     Mumbai   Phone  20000    3000         5
2    Sohan      Delhi  Tablet  15000    2000         3
3     Aman  Bangalore  Laptop  60000    9000         1
4     Neha     Mumbai   Phone  22000    3200         4
5    Priya      Delhi  Tablet  14000    1800         2
6    Karan  Bangalore  Laptop  58000    8500         2
7    Rahul     Mumbai   Phone  21000    3100         6>

In [29]:
dd["Sales"]

0    55000
1    20000
2    15000
3    60000
4    22000
5    14000
6    58000
7    21000
Name: Sales, dtype: int64

In [30]:
dd[["Sales","Profit"]]

   Sales  Profit
0  55000    8000
1  20000    3000
2  15000    2000
3  60000    9000
4  22000    3200
5  14000    1800
6  58000    8500
7  21000    3100

In [31]:
dd["Sales">30000]

TypeError: '>' not supported between instances of 'str' and 'int'

In [33]:
dd[dd["Sales"]>30000]

  Customer       City Product  Sales  Profit  Quantity
0    Mohan      Delhi  Laptop  55000    8000         2
3     Aman  Bangalore  Laptop  60000    9000         1
6    Karan  Bangalore  Laptop  58000    8500         2

In [40]:
dd[dd["City"] =="Delhi"]

  Customer   City Product  Sales  Profit  Quantity
0    Mohan  Delhi  Laptop  55000    8000         2
2    Sohan  Delhi  Tablet  15000    2000         3
5    Priya  Delhi  Tablet  14000    1800         2

In [41]:
dd[dd["Profit"]>5000]

  Customer       City Product  Sales  Profit  Quantity
0    Mohan      Delhi  Laptop  55000    8000         2
3     Aman  Bangalore  Laptop  60000    9000         1
6    Karan  Bangalore  Laptop  58000    8500         2

In [44]:
dd.sort_values(by="Sales",ascending=True)

  Customer       City Product  Sales  Profit  Quantity
5    Priya      Delhi  Tablet  14000    1800         2
2    Sohan      Delhi  Tablet  15000    2000         3
1    Rohan     Mumbai   Phone  20000    3000         5
7    Rahul     Mumbai   Phone  21000    3100         6
4     Neha     Mumbai   Phone  22000    3200         4
0    Mohan      Delhi  Laptop  55000    8000         2
6    Karan  Bangalore  Laptop  58000    8500         2
3     Aman  Bangalore  Laptop  60000    9000         1

In [46]:
dd.sort_values(by="Sales",ascending=False)

  Customer       City Product  Sales  Profit  Quantity
3     Aman  Bangalore  Laptop  60000    9000         1
6    Karan  Bangalore  Laptop  58000    8500         2
0    Mohan      Delhi  Laptop  55000    8000         2
4     Neha     Mumbai   Phone  22000    3200         4
7    Rahul     Mumbai   Phone  21000    3100         6
1    Rohan     Mumbai   Phone  20000    3000         5
2    Sohan      Delhi  Tablet  15000    2000         3
5    Priya      Delhi  Tablet  14000    1800         2

In [51]:
dd["Profit_margin"] = dd["Profit"]/dd["Sales"]

In [52]:
dd

  Customer       City Product  Sales  Profit  Quantity  Profit_margin
0    Mohan      Delhi  Laptop  55000    8000         2       0.145455
1    Rohan     Mumbai   Phone  20000    3000         5       0.150000
2    Sohan      Delhi  Tablet  15000    2000         3       0.133333
3     Aman  Bangalore  Laptop  60000    9000         1       0.150000
4     Neha     Mumbai   Phone  22000    3200         4       0.145455
5    Priya      Delhi  Tablet  14000    1800         2       0.128571
6    Karan  Bangalore  Laptop  58000    8500         2       0.146552
7    Rahul     Mumbai   Phone  21000    3100         6       0.147619

In [57]:
dd.rename(columns={"Customer":"Customer_name",
          "Sales":"Revenue",
          "Profit":"Net_Profit"},inplace=True)

In [59]:
dd[dd["Revenue"]>25000]

,Customer_name,City,Product,Revenue,Net_Profit,Quantity,Profit_margin
0,Mohan,Delhi,Laptop,55000,8000,2,0.145455
3,Aman,Bangalore,Laptop,60000,9000,1,0.150000
6,Karan,Bangalore,Laptop,58000,8500,2,0.146552

In [63]:
dd[(dd["Revenue"]>20000) & (dd["City"]=="Delhi")]

  Customer_name   City Product  Revenue  Net_Profit  Quantity  Profit_margin
0         Mohan  Delhi  Laptop    55000        8000         2       0.145455

In [66]:
dd[(dd["Revenue"]>20000) & (dd["City"] == "Bangalore")]

,Customer_name,City,Product,Revenue,Net_Profit,Quantity,Profit_margin
3,Aman,Bangalore,Laptop,60000,9000,1,0.150000
6,Karan,Bangalore,Laptop,58000,8500,2,0.146552

In [68]:
dd["City"].value_counts()

City
Delhi        3
Mumbai       3
Bangalore    2
Name: count, dtype: int64

In [76]:
dd.isnull().sum()

Customer    0
City        0
Product     0
Sales       0
Profit      1
Quantity    0
dtype: int64

In [77]:
dd.dropna(how="any")

  Customer       City Product  Sales  Profit  Quantity
0    Mohan      Delhi  Laptop  55000  8000.0         2
1    Rohan     Mumbai   Phone  20000  3000.0         5
2    Sohan      Delhi  Tablet  15000  2000.0         3
3     Aman  Bangalore  Laptop  60000  9000.0         1
4     Neha     Mumbai   Phone  22000  3200.0         4
5    Priya      Delhi  Tablet  14000  1800.0         2
6    Karan  Bangalore  Laptop  58000  8500.0         2

In [79]:
dd.isnull().sum()

Customer    0
City        0
Product     0
Sales       0
Profit      1
Quantity    0
dtype: int64

In [80]:
dd.dropna(how="all")

  Customer       City Product  Sales  Profit  Quantity
0    Mohan      Delhi  Laptop  55000  8000.0         2
1    Rohan     Mumbai   Phone  20000  3000.0         5
2    Sohan      Delhi  Tablet  15000  2000.0         3
3     Aman  Bangalore  Laptop  60000  9000.0         1
4     Neha     Mumbai   Phone  22000  3200.0         4
5    Priya      Delhi  Tablet  14000  1800.0         2
6    Karan  Bangalore  Laptop  58000  8500.0         2
7    Rahul     Mumbai   Phone  21000     NaN         6

In [81]:
dd

  Customer       City Product  Sales  Profit  Quantity
0    Mohan      Delhi  Laptop  55000  8000.0         2
1    Rohan     Mumbai   Phone  20000  3000.0         5
2    Sohan      Delhi  Tablet  15000  2000.0         3
3     Aman  Bangalore  Laptop  60000  9000.0         1
4     Neha     Mumbai   Phone  22000  3200.0         4
5    Priya      Delhi  Tablet  14000  1800.0         2
6    Karan  Bangalore  Laptop  58000  8500.0         2
7    Rahul     Mumbai   Phone  21000     NaN         6

In [82]:
dd.to_csv()

',Customer,City,Product,Sales,Profit,Quantity\r\n0,Mohan,Delhi,Laptop,55000,8000.0,2\r\n1,Rohan,Mumbai,Phone,20000,3000.0,5\r\n2,Sohan,Delhi,Tablet,15000,2000.0,3\r\n3,Aman,Bangalore,Laptop,60000,9000.0,1\r\n4,Neha,Mumbai,Phone,22000,3200.0,4\r\n5,Priya,Delhi,Tablet,14000,1800.0,2\r\n6,Karan,Bangalore,Laptop,58000,8500.0,2\r\n7,Rahul,Mumbai,Phone,21000,,6\r\n'

In [83]:
dd.to_csv

<bound method NDFrame.to_csv of   Customer       City Product  Sales  Profit  Quantity
0    Mohan      Delhi  Laptop  55000  8000.0         2
1    Rohan     Mumbai   Phone  20000  3000.0         5
2    Sohan      Delhi  Tablet  15000  2000.0         3
3     Aman  Bangalore  Laptop  60000  9000.0         1
4     Neha     Mumbai   Phone  22000  3200.0         4
5    Priya      Delhi  Tablet  14000  1800.0         2
6    Karan  Bangalore  Laptop  58000  8500.0         2
7    Rahul     Mumbai   Phone  21000     NaN         6>

In [84]:
dd.to_csv("pr_data")