In [2]:
import numpy as np
import pandas as pd

In [28]:
data = pd.DataFrame(np.random.rand(36))

In [29]:
data.head()

          0
0  0.664745
1  0.985351
2  0.143848
3  0.322106
4  0.818563

In [30]:
data = pd.DataFrame(np.random.rand(10,4))

In [10]:
data[0][1] = "harry"

C:\Users\Thisi\AppData\Local\Temp\ipykernel_13800\2537421035.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  data[0][1] = "harry"
C:\Users\Thisi\AppData\Local\Temp\ipykernel_13800\2537421035.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'harry' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  data[0][1] = "harry"

In [31]:
data

          0         1         2         3
0  0.166017  0.645033  0.423597  0.413536
1  0.891948  0.590614  0.216473  0.748107
2  0.269600  0.486330  0.163721  0.931438
3  0.790374  0.928897  0.394122  0.391876
4  0.935842  0.775874  0.118925  0.143376
5  0.804405  0.481620  0.250906  0.464788
6  0.626006  0.523925  0.664943  0.208023
7  0.747168  0.162307  0.590672  0.172468
8  0.741437  0.044433  0.702413  0.600592
9  0.843314  0.384615  0.658468  0.120444

In [12]:
data.index['first','Second']

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [33]:
data.sum(axis=0)

0    6.816112
1    5.023647
2    4.184240
3    4.194649
dtype: float64

          0         1         2         3
0  0.166017  0.645033  0.423597  0.413536
1  0.891948  0.590614  0.216473  0.748107
2  0.269600  0.486330  0.163721  0.931438
3  0.790374  0.928897  0.394122  0.391876
4  0.935842  0.775874  0.118925  0.143376
5  0.804405  0.481620  0.250906  0.464788
6  0.626006  0.523925  0.664943  0.208023
7  0.747168  0.162307  0.590672  0.172468
8  0.741437  0.044433  0.702413  0.600592
9  0.843314  0.384615  0.658468  0.120444

In [35]:
data.iloc[0]

0    0.166017
1    0.645033
2    0.423597
3    0.413536
Name: 0, dtype: float64

In [36]:
data.iloc[1]

0    0.891948
1    0.590614
2    0.216473
3    0.748107
Name: 1, dtype: float64

In [37]:
data[0]

0    0.166017
1    0.891948
2    0.269600
3    0.790374
4    0.935842
5    0.804405
6    0.626006
7    0.747168
8    0.741437
9    0.843314
Name: 0, dtype: float64

In [40]:
data.iloc[0,1]

np.float64(0.6450330481507865)

In [41]:
data

          0         1         2         3
0  0.166017  0.645033  0.423597  0.413536
1  0.891948  0.590614  0.216473  0.748107
2  0.269600  0.486330  0.163721  0.931438
3  0.790374  0.928897  0.394122  0.391876
4  0.935842  0.775874  0.118925  0.143376
5  0.804405  0.481620  0.250906  0.464788
6  0.626006  0.523925  0.664943  0.208023
7  0.747168  0.162307  0.590672  0.172468
8  0.741437  0.044433  0.702413  0.600592
9  0.843314  0.384615  0.658468  0.120444

In [42]:
data.iloc[0:2]

          0         1         2         3
0  0.166017  0.645033  0.423597  0.413536
1  0.891948  0.590614  0.216473  0.748107

In [43]:
data.iloc[0:2,0:2]

          0         1
0  0.166017  0.645033
1  0.891948  0.590614

In [56]:
data = pd.read_csv("pr_data")

In [45]:
data

   Unnamed: 0 Customer       City Product  Sales  Profit  Quantity
0           0    Mohan      Delhi  Laptop  55000  8000.0         2
1           1    Rohan     Mumbai   Phone  20000  3000.0         5
2           2    Sohan      Delhi  Tablet  15000  2000.0         3
3           3     Aman  Bangalore  Laptop  60000  9000.0         1
4           4     Neha     Mumbai   Phone  22000  3200.0         4
5           5    Priya      Delhi  Tablet  14000  1800.0         2
6           6    Karan  Bangalore  Laptop  58000  8500.0         2
7           7    Rahul     Mumbai   Phone  21000     NaN         6

In [49]:
data = pd.DataFrame(np.random.randint(0,100,(10,4)))

In [50]:
data

    0   1   2   3
0  30  91  43  95
1  50  19  86  92
2  47  70  52  29
3  25  43  14  65
4  40  24  73  58
5  15  77  85  76
6  64  23  60  89
7  96  44  15  95
8  72  51   6  64
9  72  58  46  29

In [53]:
data.loc[1,3]

np.int32(92)

    0   1   2   3
0  30  91  43  95
1  50  19  86  92
2  47  70  52  29
3  25  43  14  65
4  40  24  73  58

In [55]:
data

    0   1   2   3
0  30  91  43  95
1  50  19  86  92
2  47  70  52  29
3  25  43  14  65
4  40  24  73  58
5  15  77  85  76
6  64  23  60  89
7  96  44  15  95
8  72  51   6  64
9  72  58  46  29

In [57]:
data

   Unnamed: 0 Customer       City Product  Sales  Profit  Quantity
0           0    Mohan      Delhi  Laptop  55000  8000.0         2
1           1    Rohan     Mumbai   Phone  20000  3000.0         5
2           2    Sohan      Delhi  Tablet  15000  2000.0         3
3           3     Aman  Bangalore  Laptop  60000  9000.0         1
4           4     Neha     Mumbai   Phone  22000  3200.0         4
5           5    Priya      Delhi  Tablet  14000  1800.0         2
6           6    Karan  Bangalore  Laptop  58000  8500.0         2
7           7    Rahul     Mumbai   Phone  21000     NaN         6

In [58]:
data.drop(0,axis=1)

KeyError: '[0] not found in axis'

In [59]:
data.drop([0],axis=1)

KeyError: '[0] not found in axis'

In [68]:
data = pd.DataFrame(np.random.randint(0,1000,(20,7)))

In [69]:
data

      0    1    2    3    4    5    6
0   265  340  975  366  316  657  494
1   939  925  579  690  819  719  525
2   203   34  695  414  793  131  461
3   631  960   43  269  173   92  313
4   149   71  545  280  406  195  197
5   355  844   12  157  880   15  166
6   758  502  631  724  314  151  646
7   366  933  731  798  585  100    5
8   462  218  439  168  170  346  705
9   750  719  586  126  113  171  163
10  454  378  457  586  985  129   58
11  457  967  640  682  694  110  428
12   61  175  693   26  804  808  462
13  923  881  169  896   82  240  185
14  561  860  528  487  929  562  142
15  935  699  874  244   49  534   49
16  677  916  738  111  269  467  582
17  122  897  239  565  642  887  242
18  405  400  209  802  771  347  171
19  936  160  342  728  316  410  557

In [71]:
data[0:4]>500

       0      1      2      3      4      5      6
0  False  False   True  False  False   True  False
1   True   True   True   True   True   True   True
2  False  False   True  False   True  False  False
3   True   True  False  False  False  False  False

In [72]:
data[0]>500

0     False
1      True
2     False
3      True
4     False
5     False
6      True
7     False
8     False
9      True
10    False
11    False
12    False
13     True
14     True
15     True
16     True
17    False
18    False
19     True
Name: 0, dtype: bool

In [73]:
data[3]>500

0     False
1      True
2     False
3     False
4     False
5     False
6      True
7      True
8     False
9     False
10     True
11     True
12    False
13     True
14    False
15    False
16    False
17     True
18     True
19     True
Name: 3, dtype: bool

In [74]:
data = pd.read_csv("pr_data")

In [75]:
data

   Unnamed: 0 Customer       City Product  Sales  Profit  Quantity
0           0    Mohan      Delhi  Laptop  55000  8000.0         2
1           1    Rohan     Mumbai   Phone  20000  3000.0         5
2           2    Sohan      Delhi  Tablet  15000  2000.0         3
3           3     Aman  Bangalore  Laptop  60000  9000.0         1
4           4     Neha     Mumbai   Phone  22000  3200.0         4
5           5    Priya      Delhi  Tablet  14000  1800.0         2
6           6    Karan  Bangalore  Laptop  58000  8500.0         2
7           7    Rahul     Mumbai   Phone  21000     NaN         6

In [76]:
data.drop[0]

TypeError: 'method' object is not subscriptable

In [77]:
data.drop(0)

   Unnamed: 0 Customer       City Product  Sales  Profit  Quantity
1           1    Rohan     Mumbai   Phone  20000  3000.0         5
2           2    Sohan      Delhi  Tablet  15000  2000.0         3
3           3     Aman  Bangalore  Laptop  60000  9000.0         1
4           4     Neha     Mumbai   Phone  22000  3200.0         4
5           5    Priya      Delhi  Tablet  14000  1800.0         2
6           6    Karan  Bangalore  Laptop  58000  8500.0         2
7           7    Rahul     Mumbai   Phone  21000     NaN         6

In [78]:
data.drop(0,axis=1)

KeyError: '[0] not found in axis'

In [79]:
data.drop(0,axis=0)

   Unnamed: 0 Customer       City Product  Sales  Profit  Quantity
1           1    Rohan     Mumbai   Phone  20000  3000.0         5
2           2    Sohan      Delhi  Tablet  15000  2000.0         3
3           3     Aman  Bangalore  Laptop  60000  9000.0         1
4           4     Neha     Mumbai   Phone  22000  3200.0         4
5           5    Priya      Delhi  Tablet  14000  1800.0         2
6           6    Karan  Bangalore  Laptop  58000  8500.0         2
7           7    Rahul     Mumbai   Phone  21000     NaN         6

In [80]:
data.drop("Unnamed:0",axis=0)

KeyError: "['Unnamed:0'] not found in axis"

In [84]:
data.groupby("Product")["Sales"].sum(
)

Product
Laptop    173000
Phone      63000
Tablet     29000
Name: Sales, dtype: int64

In [88]:
data.groupby("Product")["Sales"].max()

Product
Laptop    60000
Phone     22000
Tablet    15000
Name: Sales, dtype: int64

In [90]:
data.groupby("Product").agg({
    "Sales":"sum",
    "profit":"mean"
})

KeyError: "Column(s) ['profit'] do not exist"

In [91]:
data

   Unnamed: 0 Customer       City Product  Sales  Profit  Quantity
0           0    Mohan      Delhi  Laptop  55000  8000.0         2
1           1    Rohan     Mumbai   Phone  20000  3000.0         5
2           2    Sohan      Delhi  Tablet  15000  2000.0         3
3           3     Aman  Bangalore  Laptop  60000  9000.0         1
4           4     Neha     Mumbai   Phone  22000  3200.0         4
5           5    Priya      Delhi  Tablet  14000  1800.0         2
6           6    Karan  Bangalore  Laptop  58000  8500.0         2
7           7    Rahul     Mumbai   Phone  21000     NaN         6

In [93]:
data.loc[data["Quantity"]<3]

   Unnamed: 0 Customer       City Product  Sales  Profit  Quantity
0           0    Mohan      Delhi  Laptop  55000  8000.0         2
3           3     Aman  Bangalore  Laptop  60000  9000.0         1
5           5    Priya      Delhi  Tablet  14000  1800.0         2
6           6    Karan  Bangalore  Laptop  58000  8500.0         2

In [95]:
data["Sales"]

0    55000
1    20000
2    15000
3    60000
4    22000
5    14000
6    58000
7    21000
Name: Sales, dtype: int64

In [100]:
data.iloc[[0]]

   Unnamed: 0 Customer   City Product  Sales  Profit  Quantity
0           0    Mohan  Delhi  Laptop  55000  8000.0         2

In [102]:
data[data["Profit"]>50]

   Unnamed: 0 Customer       City Product  Sales  Profit  Quantity
0           0    Mohan      Delhi  Laptop  55000  8000.0         2
1           1    Rohan     Mumbai   Phone  20000  3000.0         5
2           2    Sohan      Delhi  Tablet  15000  2000.0         3
3           3     Aman  Bangalore  Laptop  60000  9000.0         1
4           4     Neha     Mumbai   Phone  22000  3200.0         4
5           5    Priya      Delhi  Tablet  14000  1800.0         2
6           6    Karan  Bangalore  Laptop  58000  8500.0         2

TypeError: Cannot index by location index with a non-integer key

In [105]:
data[["Sales","Profit"]]

   Sales  Profit
0  55000  8000.0
1  20000  3000.0
2  15000  2000.0
3  60000  9000.0
4  22000  3200.0
5  14000  1800.0
6  58000  8500.0
7  21000     NaN

In [106]:
data.loc["Sales"]>100

KeyError: 'Sales'

In [111]:
data[data["Sales"]>100]["Profit"]

0    8000.0
1    3000.0
2    2000.0
3    9000.0
4    3200.0
5    1800.0
6    8500.0
7       NaN
Name: Profit, dtype: float64

In [112]:
data[data["Sales"]>100]["Profit"]

0    8000.0
1    3000.0
2    2000.0
3    9000.0
4    3200.0
5    1800.0
6    8500.0
7       NaN
Name: Profit, dtype: float64

In [113]:
data[data["Sales"]>100]["Profit"]

0    8000.0
1    3000.0
2    2000.0
3    9000.0
4    3200.0
5    1800.0
6    8500.0
7       NaN
Name: Profit, dtype: float64

In [115]:
data[data["City"]=="Delhi"]

   Unnamed: 0 Customer   City Product  Sales  Profit  Quantity
0           0    Mohan  Delhi  Laptop  55000  8000.0         2
2           2    Sohan  Delhi  Tablet  15000  2000.0         3
5           5    Priya  Delhi  Tablet  14000  1800.0         2

In [117]:
data[data["Sales"]>50000]

   Unnamed: 0 Customer       City Product  Sales  Profit  Quantity
0           0    Mohan      Delhi  Laptop  55000  8000.0         2
3           3     Aman  Bangalore  Laptop  60000  9000.0         1
6           6    Karan  Bangalore  Laptop  58000  8500.0         2

In [118]:
data[["Customer","Product"]]

  Customer Product
0    Mohan  Laptop
1    Rohan   Phone
2    Sohan  Tablet
3     Aman  Laptop
4     Neha   Phone
5    Priya  Tablet
6    Karan  Laptop
7    Rahul   Phone

In [119]:
data["Product"]==["Laptop"]

ValueError: ('Lengths must match to compare', (8,), (1,))

In [122]:
data[data["Product"]=="Laptop"]

   Unnamed: 0 Customer       City Product  Sales  Profit  Quantity
0           0    Mohan      Delhi  Laptop  55000  8000.0         2
3           3     Aman  Bangalore  Laptop  60000  9000.0         1
6           6    Karan  Bangalore  Laptop  58000  8500.0         2

In [130]:
data[data["Profit"]>3000,["Customer"],["Sales"]

_IncompleteInputError: incomplete input (4235857324.py, line 1)

In [134]:
data[data["Sales"]>3000][["Customer","Sales"]]

  Customer  Sales
0    Mohan  55000
1    Rohan  20000
2    Sohan  15000
3     Aman  60000
4     Neha  22000
5    Priya  14000
6    Karan  58000
7    Rahul  21000