In [4]:
import pandas as pd
import numpy as np
import os

In [15]:
data = {
    "Name": ["Riya", "Aman", "Raj", "Neha", "Karan", "Simran"],
    "Age": [23, np.nan, 29, 31, np.nan, 26],
    "Salary": [50000, 60000, np.nan, 58000, 62000, np.nan],
    "Department": ["HR", "IT", "Finance", np.nan, "IT", "HR"]
}


data = pd.DataFrame(data)

In [11]:
data["Age"] = np.nan

In [12]:
data

     Name  Age   Salary Department
0    Riya  NaN  50000.0         HR
1    Aman  NaN  60000.0         IT
2     Raj  NaN      NaN    Finance
3    Neha  NaN  58000.0        NaN
4   Karan  NaN  62000.0         IT
5  Simran  NaN      NaN         HR

In [17]:
data.dropna(how="all",axis=1)

     Name   Age   Salary Department
0    Riya  23.0  50000.0         HR
1    Aman   NaN  60000.0         IT
2     Raj  29.0      NaN    Finance
3    Neha  31.0  58000.0        NaN
4   Karan   NaN  62000.0         IT
5  Simran  26.0      NaN         HR

In [20]:
data["Name"]=np.nan

In [21]:
data

   Name   Age   Salary Department
0   NaN  23.0  50000.0         HR
1   NaN   NaN  60000.0         IT
2   NaN  29.0      NaN    Finance
3   NaN  31.0  58000.0        NaN
4   NaN   NaN  62000.0         IT
5   NaN  26.0      NaN         HR

In [22]:
data.dropna(how="all",axis=1)

    Age   Salary Department
0  23.0  50000.0         HR
1   NaN  60000.0         IT
2  29.0      NaN    Finance
3  31.0  58000.0        NaN
4   NaN  62000.0         IT
5  26.0      NaN         HR

In [23]:
data

   Name   Age   Salary Department
0   NaN  23.0  50000.0         HR
1   NaN   NaN  60000.0         IT
2   NaN  29.0      NaN    Finance
3   NaN  31.0  58000.0        NaN
4   NaN   NaN  62000.0         IT
5   NaN  26.0      NaN         HR

In [24]:
data_dup = {
    "Name": ["Riya", "Aman", "Raj", "Neha", "Karan", "Simran"],
    "Age": [23, np.nan, 29, 31, np.nan, 26],
    "Salary": [50000, 60000, np.nan, 58000, 62000, np.nan],
    "Department": ["IT", "IT", "IT", "IT", "IT", "IT"]
}
df_dup =pd.DataFrame(data_dup)

In [25]:
df_dup

     Name   Age   Salary Department
0    Riya  23.0  50000.0         IT
1    Aman   NaN  60000.0         IT
2     Raj  29.0      NaN         IT
3    Neha  31.0  58000.0         IT
4   Karan   NaN  62000.0         IT
5  Simran  26.0      NaN         IT

In [27]:
df_dup.drop_duplicates(subset="Name")

     Name   Age   Salary Department
0    Riya  23.0  50000.0         IT
1    Aman   NaN  60000.0         IT
2     Raj  29.0      NaN         IT
3    Neha  31.0  58000.0         IT
4   Karan   NaN  62000.0         IT
5  Simran  26.0      NaN         IT

In [28]:
data = {
    "Name": ["Aman", "Riya", "Aman", "Karan", "Riya"],
    "Age": [23, 25, 23, 24, 25],
    "City": ["Delhi", "Mumbai", "Delhi", "Pune", "Mumbai"]
}
df = pd.DataFrame(data)

In [29]:
df

    Name  Age    City
0   Aman   23   Delhi
1   Riya   25  Mumbai
2   Aman   23   Delhi
3  Karan   24    Pune
4   Riya   25  Mumbai

In [30]:
df.drop_duplicates(subset="Name")

    Name  Age    City
0   Aman   23   Delhi
1   Riya   25  Mumbai
3  Karan   24    Pune

In [35]:
df[df.duplicated(subset=["Name"],keep=False)]

   Name  Age    City
0  Aman   23   Delhi
1  Riya   25  Mumbai
2  Aman   23   Delhi
4  Riya   25  Mumbai

In [36]:
data = pd.read_csv("actuals")

FileNotFoundError: [Errno 2] No such file or directory: 'actuals'

In [46]:
data = pd.read_excel(r"C:\Users\Thisi\OneDrive\Documents\datasets\Dataset 1\orders.xlsx")

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Thisi\\OneDrive\\Documents\\datasets\\Dataset 1\\orders.xlsx'

In [48]:
df = pd.read_excel(r"C:\Users\Thisi\OneDrive\Documents\datasets\Dataset 1\orders.xlsx")

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Thisi\\OneDrive\\Documents\\datasets\\Dataset 1\\orders.xlsx'

In [50]:
os.listdir(r"C:\Users\Thisi\OneDrive\Documents\datasets\Dataset 1")

['category.csv',
 'class.csv',
 'groups.csv',
 'membership.csv',
 'orders.xlsx.csv',
 'order_details.csv',
 'person1.csv',
 'person2.csv',
 'students.csv',
 'users.csv',
 'users1.csv']

In [53]:
data = pd.read_csv(r"C:\Users\Thisi\OneDrive\Documents\datasets\Dataset 1\order_details.csv")

In [54]:
data

     order_id  amount  profit  quantity  category_id
0     B-25601  1275.0 -1148.0         7            1
1     B-25614   494.0    54.0         4            1
2     B-25618   362.0   127.0         1            1
3     B-25638   182.0   -11.0         3            1
4     B-25643  1061.0   -36.0         8            1
...       ...     ...     ...       ...          ...
1495  B-26053    17.0     1.0         2           65
1496  B-26053    27.0     6.0         3           65
1497  B-26078    17.0     8.0         2           65
1498  B-26098    46.0    14.0         5           65
1499  B-26099     9.0     3.0         1           65

[1500 rows x 5 columns]

In [59]:
df = pd.read_excel(r"C:\Users\Thisi\Downloads\SuperStore Sales Data-20260306T171841Z-3-001\SuperStore Sales Data\Sales_Dataset.xlsx")

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

In [60]:
os.listdir(r"C:\Users\Thisi\Downloads\SuperStore Sales Data-20260306T171841Z-3-001\SuperStore Sales Data")

['blue bg.jpg', 'Sales_DataSet.xlsx', 'SuperStore_Sales_Dataset.csv']

In [62]:
data = pd.read_excel(r"C:\Users\Thisi\Downloads\SuperStore Sales Data-20260306T171841Z-3-001\SuperStore Sales Data\Sales_Dataset.xlsx")

In [63]:
data

,Row ID+O6G3A1:R6,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Profit,Returns,Payment Mode,ind1,ind2
0,4918,CA-2019-160304,2019-01-01,2019-01-07,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",73.940,1,28.2668,NaN,Online,NaN,NaN
1,4919,CA-2019-160304,2019-01-02,2019-01-07,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",173.940,3,38.2668,NaN,Online,NaN,NaN
2,4920,CA-2019-160304,2019-01-02,2019-01-07,Standard Class,BM-11575,Brendan Murry,Corporate,United States,Gaithersburg,...,Technology,Phones,GE 30522EE2,231.980,2,67.2742,NaN,Cards,NaN,NaN
3,3074,CA-2019-125206,2019-01-03,2019-01-05,First Class,LR-16915,Lena Radford,Consumer,United States,Los Angeles,...,Office Supplies,Storage,Recycled Steel Personal File for Hanging File ...,114.460,2,28.6150,NaN,Online,NaN,NaN
4,8604,US-2019-116365,2019-01-03,2019-01-08,Standard Class,CA-12310,Christine Abelman,Corporate,United States,San Antonio,...,Technology,Accessories,Imation Clip USB flash drive - 8 GB,30.080,2,-5.2640,NaN,Online,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5896,907,CA-2020-143259,2020-12-30,2021-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Fully Ass...",213.136,4,12.1176,NaN,COD,NaN,NaN
5897,1297,CA-2020-115427,2020-12-30,2021-01-03,Standard Class,EB-13975,Erica Bern,Corporate,United States,Fairfield,...,Office Supplies,Binders,"Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl",295.904,2,4.5188,1.0,Online,NaN,NaN
5898,5092,CA-2020-156720,2020-12-30,2021-01-03,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,Office Supplies,Fasteners,Bagged Rubber Bands,388.024,3,-0.6048,NaN,Online,NaN,NaN
5899,909,CA-2020-143259,2020-12-30,2021-01-03,Standard Class,PO-18865,Patrick O'Donnell,Consumer,United States,New York City,...,Office Supplies,Binders,Wilson Jones Legal Size Ring Binders,462.776,3,19.7910,NaN,COD,NaN,NaN
5900,5093,CA-2020-151450,2020-12-31,2021-01-04,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,Office Supplies,Fasteners,Bagged Rubber Bands,2975.510,3,-0.6048,NaN,COD,NaN,NaN

In [64]:
df.shape()

TypeError: 'tuple' object is not callable

In [65]:
data.shape(

)

TypeError: 'tuple' object is not callable

In [66]:
data.shape

(5901, 23)

In [67]:
df.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [68]:
dff.info()

NameError: name 'dff' is not defined

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes

In [1]:
df

NameError: name 'df' is not defined

In [2]:
dd

NameError: name 'dd' is not defined

In [3]:
data = pd.DataFrame("pr1_ds")

NameError: name 'pd' is not defined