In [1]:
import numpy as np
import pandas as pd

In [8]:
data = pd.DataFrame(np.random.randint(0,1000,(30,5)))

In [11]:
data.head()

     0    1    2    3    4
0   82  519  968  852  107
1  429  592  492  182  289
2  740  297  804  540   50
3  620  519   73  396  583
4  774  643  447  523  124

In [124]:
data = {
    "Name": ["Aman", "Riya", "Karan", "Neha", "Rahul"],
    "Age": [23, 25, 24, 22, 26],
    "Salary": [50000, 60000, 55000, 52000, 65000],
    "Department": ["HR", "IT", "IT", "Finance", "HR"]
}

df = pd.DataFrame(data)
df.to_csv("pr1_ds")

In [17]:
df.loc[0,1]

KeyError: 1

In [19]:
df.loc[[0]]

   Name  Age  Salary Department
0  Aman   23   50000         HR

In [20]:
df.loc[["Salary",3]]

KeyError: "['Salary'] not in index"

In [21]:
df.loc["Salary",3]

KeyError: 3

In [22]:
df.loc[2,"Salary"]

np.int64(55000)

In [24]:
df[["Name","Salary"]]

    Name  Salary
0   Aman   50000
1   Riya   60000
2  Karan   55000
3   Neha   52000
4  Rahul   65000

In [29]:
df.loc[[1]]

   Name  Age  Salary Department
1  Riya   25   60000         IT

In [30]:
df.loc[1,"Salary"]

np.int64(60000)

In [31]:
df.loc[1:3]

    Name  Age  Salary Department
1   Riya   25   60000         IT
2  Karan   24   55000         IT
3   Neha   22   52000    Finance

In [32]:
df.loc["Riya","Age"]

KeyError: 'Riya'

In [35]:
df[df["Name"]=="Riya",df["Age"]]

InvalidIndexError: (0    False
1     True
2    False
3    False
4    False
Name: Name, dtype: bool, 0    23
1    25
2    24
3    22
4    26
Name: Age, dtype: int64)

In [48]:
df.loc[df["Name"]=="Riya"]

   Name  Age  Salary Department
1  Riya   25   60000         IT

In [55]:
df.iloc[4,2]

np.int64(65000)

In [64]:
df.iloc[1:4,[0,2]]

    Name  Salary
1   Riya   60000
2  Karan   55000
3   Neha   52000

In [66]:
df[df["Salary"]>55000]

    Name  Age  Salary Department
1   Riya   25   60000         IT
4  Rahul   26   65000         HR

In [67]:
df[df["Department"] == "IT"]

    Name  Age  Salary Department
1   Riya   25   60000         IT
2  Karan   24   55000         IT

In [68]:
df

    Name  Age  Salary Department
0   Aman   23   50000         HR
1   Riya   25   60000         IT
2  Karan   24   55000         IT
3   Neha   22   52000    Finance
4  Rahul   26   65000         HR

In [69]:
df.iloc[4,2]

np.int64(65000)

In [74]:
df.iloc[1:4,[0,2]]

    Name  Salary
1   Riya   60000
2  Karan   55000
3   Neha   52000

In [75]:
df.iloc[2,1]

np.int64(24)

In [78]:
df.iloc[0:3,[0]]

    Name
0   Aman
1   Riya
2  Karan

In [80]:
df.loc[df["Name"]=="Riya",["Age"]]

   Age
1   25

In [83]:
df.loc[df["Name"]=="Neha",["Salary"]]

   Salary
3   52000

In [84]:
df.iloc[1:4,[1,3]]

   Age Department
1   25         IT
2   24         IT
3   22    Finance

In [92]:
df.drop("Name",axis=1)

   Age  Salary Department
0   23   50000         HR
1   25   60000         IT
2   24   55000         IT
3   22   52000    Finance
4   26   65000         HR

In [93]:
df

    Name  Age  Salary Department
0   Aman   23   50000         HR
1   Riya   25   60000         IT
2  Karan   24   55000         IT
3   Neha   22   52000    Finance
4  Rahul   26   65000         HR

In [95]:
df.drop(["Name","Salary"],axis=1)

   Age Department
0   23         HR
1   25         IT
2   24         IT
3   22    Finance
4   26         HR

In [96]:
df.drop([1,2])

    Name  Age  Salary Department
0   Aman   23   50000         HR
3   Neha   22   52000    Finance
4  Rahul   26   65000         HR

In [97]:
df.drop("columns"="Age")

SyntaxError: expression cannot contain assignment, perhaps you meant "=="? (4171441370.py, line 1)

In [98]:
df.drop(columns="Age")

    Name  Salary Department
0   Aman   50000         HR
1   Riya   60000         IT
2  Karan   55000         IT
3   Neha   52000    Finance
4  Rahul   65000         HR

In [101]:
df.drop(index=2,axis=1)

    Name  Age  Salary Department
0   Aman   23   50000         HR
1   Riya   25   60000         IT
3   Neha   22   52000    Finance
4  Rahul   26   65000         HR

In [102]:
df

    Name  Age  Salary Department
0   Aman   23   50000         HR
1   Riya   25   60000         IT
2  Karan   24   55000         IT
3   Neha   22   52000    Finance
4  Rahul   26   65000         HR

In [103]:
df.drop("Salary",axis=1)

    Name  Age Department
0   Aman   23         HR
1   Riya   25         IT
2  Karan   24         IT
3   Neha   22    Finance
4  Rahul   26         HR

In [104]:
df.drop(["Age","Department"],axis=1)

    Name  Salary
0   Aman   50000
1   Riya   60000
2  Karan   55000
3   Neha   52000
4  Rahul   65000

In [105]:
df.drop(4)

    Name  Age  Salary Department
0   Aman   23   50000         HR
1   Riya   25   60000         IT
2  Karan   24   55000         IT
3   Neha   22   52000    Finance

In [107]:
df.drop([1:4])

SyntaxError: invalid syntax (926550386.py, line 1)

In [109]:
df.drop("Age",axis=1)

    Name  Salary Department
0   Aman   50000         HR
1   Riya   60000         IT
2  Karan   55000         IT
3   Neha   52000    Finance
4  Rahul   65000         HR

In [110]:
df.drop([1,3])

    Name  Age  Salary Department
0   Aman   23   50000         HR
2  Karan   24   55000         IT
4  Rahul   26   65000         HR

In [113]:
df.drop(df.index[1:4],axis=0)

    Name  Age  Salary Department
0   Aman   23   50000         HR
4  Rahul   26   65000         HR

In [114]:
df.reset_index()

   index   Name  Age  Salary Department
0      0   Aman   23   50000         HR
1      1   Riya   25   60000         IT
2      2  Karan   24   55000         IT
3      3   Neha   22   52000    Finance
4      4  Rahul   26   65000         HR

In [115]:
df.drop("index")

KeyError: "['index'] not found in axis"

In [116]:
df.drop(index=True,inplace="True")

ValueError: For argument "inplace" expected type bool, received type str.

In [117]:
df.reset_index(drop=True,inplace=True)

In [118]:
df

    Name  Age  Salary Department
0   Aman   23   50000         HR
1   Riya   25   60000         IT
2  Karan   24   55000         IT
3   Neha   22   52000    Finance
4  Rahul   26   65000         HR

In [120]:
df.loc[:,["Name","Age"]]=56

In [129]:
data = pd.read_csv("pr1_ds")

In [130]:
data

   Unnamed: 0   Name  Age  Salary Department
0           0   Aman   23   50000         HR
1           1   Riya   25   60000         IT
2           2  Karan   24   55000         IT
3           3   Neha   22   52000    Finance
4           4  Rahul   26   65000         HR

In [131]:
data.drop(1)

   Unnamed: 0   Name  Age  Salary Department
0           0   Aman   23   50000         HR
2           2  Karan   24   55000         IT
3           3   Neha   22   52000    Finance
4           4  Rahul   26   65000         HR

In [132]:
data

   Unnamed: 0   Name  Age  Salary Department
0           0   Aman   23   50000         HR
1           1   Riya   25   60000         IT
2           2  Karan   24   55000         IT
3           3   Neha   22   52000    Finance
4           4  Rahul   26   65000         HR

In [135]:
data.columns[1]

'Name'

In [136]:
data

   Unnamed: 0   Name  Age  Salary Department
0           0   Aman   23   50000         HR
1           1   Riya   25   60000         IT
2           2  Karan   24   55000         IT
3           3   Neha   22   52000    Finance
4           4  Rahul   26   65000         HR

In [139]:
data.drop(data.columns[1],axis= 1)

   Unnamed: 0  Age  Salary Department
0           0   23   50000         HR
1           1   25   60000         IT
2           2   24   55000         IT
3           3   22   52000    Finance
4           4   26   65000         HR

In [140]:
data

   Unnamed: 0   Name  Age  Salary Department
0           0   Aman   23   50000         HR
1           1   Riya   25   60000         IT
2           2  Karan   24   55000         IT
3           3   Neha   22   52000    Finance
4           4  Rahul   26   65000         HR

In [143]:
data.drop(data.columns[0],axis=1,inplace= True)

In [144]:
data

    Name  Age  Salary Department
0   Aman   23   50000         HR
1   Riya   25   60000         IT
2  Karan   24   55000         IT
3   Neha   22   52000    Finance
4  Rahul   26   65000         HR