In [3]:
import pandas as pd

In [4]:
s = pd.Series([1,2,3,6,6,7])
s

0    1
1    2
2    3
3    6
4    6
5    7
dtype: int64

In [5]:
s.name = "numbers"

In [6]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [7]:
s

0    1
1    2
2    3
3    6
4    6
5    7
Name: numbers, dtype: int64

In [8]:
s2 =pd.Series(myfruits,name=("number"))

NameError: name 'myfruits' is not defined

In [ ]:
s2

Avocado    2.0
Guava      2.1
mango      1.0
cherry     2.0
Name: number, dtype: float64

In [ ]:
s2[s2>1]

Avocado    2.0
Guava      2.1
cherry     2.0
Name: number, dtype: float64

In [ ]:
s2

NameError: name 's2' is not defined

In [10]:
dataset = {
     "OrderID": [101,102,103,104,105,106,107,108,109,110],
    "Customer": ["Riya","Aman","Karan","Riya","Aman","Neha","Karan","Riya","Neha","Aman"],
    "City": ["Delhi","Mumbai","Delhi","Delhi","Mumbai","Pune","Delhi","Pune","Mumbai","Delhi"],
    "Product": ["Laptop","Mouse","Keyboard","Laptop","Keyboard","Mouse","Laptop","Mouse","Keyboard","Laptop"],
    "Quantity": [1,2,1,1,3,2,1,2,1,1],
    "Price": [50000,500,1500,52000,1400,600,51000,550,1600,53000],
    "OrderDate": [
        "2024-01-05","2024-01-06","2024-01-07","2024-01-10","2024-01-12",
        "2024-01-13","2024-01-15","2024-01-18","2024-01-20","2024-01-22"
    ]
}

df = pd.DataFrame(dataset)
df

   OrderID Customer    City   Product  Quantity  Price   OrderDate
0      101     Riya   Delhi    Laptop         1  50000  2024-01-05
1      102     Aman  Mumbai     Mouse         2    500  2024-01-06
2      103    Karan   Delhi  Keyboard         1   1500  2024-01-07
3      104     Riya   Delhi    Laptop         1  52000  2024-01-10
4      105     Aman  Mumbai  Keyboard         3   1400  2024-01-12
5      106     Neha    Pune     Mouse         2    600  2024-01-13
6      107    Karan   Delhi    Laptop         1  51000  2024-01-15
7      108     Riya    Pune     Mouse         2    550  2024-01-18
8      109     Neha  Mumbai  Keyboard         1   1600  2024-01-20
9      110     Aman   Delhi    Laptop         1  53000  2024-01-22

In [ ]:
df.to_csv("pr2_ds")

In [ ]:
df.tail(3)

   OrderID Customer    City   Product  Quantity  Price   OrderDate
7      108     Riya    Pune     Mouse         2    550  2024-01-18
8      109     Neha  Mumbai  Keyboard         1   1600  2024-01-20
9      110     Aman   Delhi    Laptop         1  53000  2024-01-22

In [ ]:
df[["Customer","Product"]]

  Customer   Product
0     Riya    Laptop
1     Aman     Mouse
2    Karan  Keyboard
3     Riya    Laptop
4     Aman  Keyboard
5     Neha     Mouse
6    Karan    Laptop
7     Riya     Mouse
8     Neha  Keyboard
9     Aman    Laptop

In [ ]:
df.iloc[[3]]

   OrderID Customer   City Product  Quantity  Price   OrderDate
3      104     Riya  Delhi  Laptop         1  52000  2024-01-10

In [ ]:
df.iloc[2:6]

   OrderID Customer    City   Product  Quantity  Price   OrderDate
2      103    Karan   Delhi  Keyboard         1   1500  2024-01-07
3      104     Riya   Delhi    Laptop         1  52000  2024-01-10
4      105     Aman  Mumbai  Keyboard         3   1400  2024-01-12
5      106     Neha    Pune     Mouse         2    600  2024-01-13

In [ ]:
df.loc["Customer","Price"]

KeyError: 'Customer'

In [ ]:
df.loc[:,["Product","Price"]]

    Product  Price
0    Laptop  50000
1     Mouse    500
2  Keyboard   1500
3    Laptop  52000
4  Keyboard   1400
5     Mouse    600
6    Laptop  51000
7     Mouse    550
8  Keyboard   1600
9    Laptop  53000

In [ ]:
df.dtypes

OrderID       int64
Customer     object
City         object
Product      object
Quantity      int64
Price         int64
OrderDate    object
dtype: object

In [ ]:
df.info

<bound method DataFrame.info of    OrderID Customer    City   Product  Quantity  Price   OrderDate
0      101     Riya   Delhi    Laptop         1  50000  2024-01-05
1      102     Aman  Mumbai     Mouse         2    500  2024-01-06
2      103    Karan   Delhi  Keyboard         1   1500  2024-01-07
3      104     Riya   Delhi    Laptop         1  52000  2024-01-10
4      105     Aman  Mumbai  Keyboard         3   1400  2024-01-12
5      106     Neha    Pune     Mouse         2    600  2024-01-13
6      107    Karan   Delhi    Laptop         1  51000  2024-01-15
7      108     Riya    Pune     Mouse         2    550  2024-01-18
8      109     Neha  Mumbai  Keyboard         1   1600  2024-01-20
9      110     Aman   Delhi    Laptop         1  53000  2024-01-22>

In [ ]:
df.columns

Index(['OrderID', 'Customer', 'City', 'Product', 'Quantity', 'Price',
       'OrderDate'],
      dtype='object')

In [ ]:
df[df["City"] == "Delhi"]

   OrderID Customer   City   Product  Quantity  Price   OrderDate
0      101     Riya  Delhi    Laptop         1  50000  2024-01-05
2      103    Karan  Delhi  Keyboard         1   1500  2024-01-07
3      104     Riya  Delhi    Laptop         1  52000  2024-01-10
6      107    Karan  Delhi    Laptop         1  51000  2024-01-15
9      110     Aman  Delhi    Laptop         1  53000  2024-01-22

In [ ]:
df[df["Price"]>50000]

   OrderID Customer   City Product  Quantity  Price   OrderDate
3      104     Riya  Delhi  Laptop         1  52000  2024-01-10
6      107    Karan  Delhi  Laptop         1  51000  2024-01-15
9      110     Aman  Delhi  Laptop         1  53000  2024-01-22

In [ ]:
df[df["Customer"]=="Riya"]

   OrderID Customer   City Product  Quantity  Price   OrderDate
0      101     Riya  Delhi  Laptop         1  50000  2024-01-05
3      104     Riya  Delhi  Laptop         1  52000  2024-01-10
7      108     Riya   Pune   Mouse         2    550  2024-01-18

In [ ]:
df[(df["City"]=="Mumbai") & (df["Quantity"]>1)]

   OrderID Customer    City   Product  Quantity  Price   OrderDate
1      102     Aman  Mumbai     Mouse         2    500  2024-01-06
4      105     Aman  Mumbai  Keyboard         3   1400  2024-01-12

In [ ]:
df[df["Product"]=="Laptop"]

   OrderID Customer   City Product  Quantity  Price   OrderDate
0      101     Riya  Delhi  Laptop         1  50000  2024-01-05
3      104     Riya  Delhi  Laptop         1  52000  2024-01-10
6      107    Karan  Delhi  Laptop         1  51000  2024-01-15
9      110     Aman  Delhi  Laptop         1  53000  2024-01-22

In [ ]:
df["Total"] = df["Quantity"] * df["Price"]

In [ ]:
df

   OrderID Customer    City   Product  Quantity  Price   OrderDate  Total
0      101     Riya   Delhi    Laptop         1  50000  2024-01-05  50000
1      102     Aman  Mumbai     Mouse         2    500  2024-01-06   1000
2      103    Karan   Delhi  Keyboard         1   1500  2024-01-07   1500
3      104     Riya   Delhi    Laptop         1  52000  2024-01-10  52000
4      105     Aman  Mumbai  Keyboard         3   1400  2024-01-12   4200
5      106     Neha    Pune     Mouse         2    600  2024-01-13   1200
6      107    Karan   Delhi    Laptop         1  51000  2024-01-15  51000
7      108     Riya    Pune     Mouse         2    550  2024-01-18   1100
8      109     Neha  Mumbai  Keyboard         1   1600  2024-01-20   1600
9      110     Aman   Delhi    Laptop         1  53000  2024-01-22  53000

In [ ]:
df[["Customer","Total"]]

  Customer  Total
0     Riya  50000
1     Aman   1000
2    Karan   1500
3     Riya  52000
4     Aman   4200
5     Neha   1200
6    Karan  51000
7     Riya   1100
8     Neha   1600
9     Aman  53000

In [ ]:
df.rename(columns={"Customer":"Customer_name"},inplace=True)

In [ ]:
df

   OrderID Customer_name    City   Product  Quantity  Price   OrderDate  Total
0      101          Riya   Delhi    Laptop         1  50000  2024-01-05  50000
1      102          Aman  Mumbai     Mouse         2    500  2024-01-06   1000
2      103         Karan   Delhi  Keyboard         1   1500  2024-01-07   1500
3      104          Riya   Delhi    Laptop         1  52000  2024-01-10  52000
4      105          Aman  Mumbai  Keyboard         3   1400  2024-01-12   4200
5      106          Neha    Pune     Mouse         2    600  2024-01-13   1200
6      107         Karan   Delhi    Laptop         1  51000  2024-01-15  51000
7      108          Riya    Pune     Mouse         2    550  2024-01-18   1100
8      109          Neha  Mumbai  Keyboard         1   1600  2024-01-20   1600
9      110          Aman   Delhi    Laptop         1  53000  2024-01-22  53000

In [ ]:
df.rename(columns={"OrderID":"ID"})

    ID Customer_name    City   Product  Quantity  Price   OrderDate  Total
0  101          Riya   Delhi    Laptop         1  50000  2024-01-05  50000
1  102          Aman  Mumbai     Mouse         2    500  2024-01-06   1000
2  103         Karan   Delhi  Keyboard         1   1500  2024-01-07   1500
3  104          Riya   Delhi    Laptop         1  52000  2024-01-10  52000
4  105          Aman  Mumbai  Keyboard         3   1400  2024-01-12   4200
5  106          Neha    Pune     Mouse         2    600  2024-01-13   1200
6  107         Karan   Delhi    Laptop         1  51000  2024-01-15  51000
7  108          Riya    Pune     Mouse         2    550  2024-01-18   1100
8  109          Neha  Mumbai  Keyboard         1   1600  2024-01-20   1600
9  110          Aman   Delhi    Laptop         1  53000  2024-01-22  53000

In [14]:
df.rename(columns={"OrderDate":"Order"},inplace=True)

In [15]:
df

   OrderID Customer    City   Product  Quantity  Price       Order
0      101     Riya   Delhi    Laptop         1  50000  2024-01-05
1      102     Aman  Mumbai     Mouse         2    500  2024-01-06
2      103    Karan   Delhi  Keyboard         1   1500  2024-01-07
3      104     Riya   Delhi    Laptop         1  52000  2024-01-10
4      105     Aman  Mumbai  Keyboard         3   1400  2024-01-12
5      106     Neha    Pune     Mouse         2    600  2024-01-13
6      107    Karan   Delhi    Laptop         1  51000  2024-01-15
7      108     Riya    Pune     Mouse         2    550  2024-01-18
8      109     Neha  Mumbai  Keyboard         1   1600  2024-01-20
9      110     Aman   Delhi    Laptop         1  53000  2024-01-22

In [16]:
df.drop(columns="Order")

   OrderID Customer    City   Product  Quantity  Price
0      101     Riya   Delhi    Laptop         1  50000
1      102     Aman  Mumbai     Mouse         2    500
2      103    Karan   Delhi  Keyboard         1   1500
3      104     Riya   Delhi    Laptop         1  52000
4      105     Aman  Mumbai  Keyboard         3   1400
5      106     Neha    Pune     Mouse         2    600
6      107    Karan   Delhi    Laptop         1  51000
7      108     Riya    Pune     Mouse         2    550
8      109     Neha  Mumbai  Keyboard         1   1600
9      110     Aman   Delhi    Laptop         1  53000

In [17]:
df

   OrderID Customer    City   Product  Quantity  Price       Order
0      101     Riya   Delhi    Laptop         1  50000  2024-01-05
1      102     Aman  Mumbai     Mouse         2    500  2024-01-06
2      103    Karan   Delhi  Keyboard         1   1500  2024-01-07
3      104     Riya   Delhi    Laptop         1  52000  2024-01-10
4      105     Aman  Mumbai  Keyboard         3   1400  2024-01-12
5      106     Neha    Pune     Mouse         2    600  2024-01-13
6      107    Karan   Delhi    Laptop         1  51000  2024-01-15
7      108     Riya    Pune     Mouse         2    550  2024-01-18
8      109     Neha  Mumbai  Keyboard         1   1600  2024-01-20
9      110     Aman   Delhi    Laptop         1  53000  2024-01-22

In [19]:
df.sort_values("Price",ascending=True)

   OrderID Customer    City   Product  Quantity  Price       Order
1      102     Aman  Mumbai     Mouse         2    500  2024-01-06
7      108     Riya    Pune     Mouse         2    550  2024-01-18
5      106     Neha    Pune     Mouse         2    600  2024-01-13
4      105     Aman  Mumbai  Keyboard         3   1400  2024-01-12
2      103    Karan   Delhi  Keyboard         1   1500  2024-01-07
8      109     Neha  Mumbai  Keyboard         1   1600  2024-01-20
0      101     Riya   Delhi    Laptop         1  50000  2024-01-05
6      107    Karan   Delhi    Laptop         1  51000  2024-01-15
3      104     Riya   Delhi    Laptop         1  52000  2024-01-10
9      110     Aman   Delhi    Laptop         1  53000  2024-01-22

In [20]:
df.sort_values("Quantity",ascending=False)

   OrderID Customer    City   Product  Quantity  Price       Order
4      105     Aman  Mumbai  Keyboard         3   1400  2024-01-12
1      102     Aman  Mumbai     Mouse         2    500  2024-01-06
7      108     Riya    Pune     Mouse         2    550  2024-01-18
5      106     Neha    Pune     Mouse         2    600  2024-01-13
0      101     Riya   Delhi    Laptop         1  50000  2024-01-05
3      104     Riya   Delhi    Laptop         1  52000  2024-01-10
2      103    Karan   Delhi  Keyboard         1   1500  2024-01-07
6      107    Karan   Delhi    Laptop         1  51000  2024-01-15
8      109     Neha  Mumbai  Keyboard         1   1600  2024-01-20
9      110     Aman   Delhi    Laptop         1  53000  2024-01-22

In [25]:
df.sort_values(by=["Price","Order"],ascending=True)

   OrderID Customer    City   Product  Quantity  Price       Order
1      102     Aman  Mumbai     Mouse         2    500  2024-01-06
7      108     Riya    Pune     Mouse         2    550  2024-01-18
5      106     Neha    Pune     Mouse         2    600  2024-01-13
4      105     Aman  Mumbai  Keyboard         3   1400  2024-01-12
2      103    Karan   Delhi  Keyboard         1   1500  2024-01-07
8      109     Neha  Mumbai  Keyboard         1   1600  2024-01-20
0      101     Riya   Delhi    Laptop         1  50000  2024-01-05
6      107    Karan   Delhi    Laptop         1  51000  2024-01-15
3      104     Riya   Delhi    Laptop         1  52000  2024-01-10
9      110     Aman   Delhi    Laptop         1  53000  2024-01-22

In [27]:
df.groupby("Product").sum()

,OrderID,Customer,City,Quantity,Price,Order
Product,,,,,,
Keyboard,317,KaranAmanNeha,DelhiMumbaiMumbai,5,4500,2024-01-072024-01-122024-01-20
Laptop,422,RiyaRiyaKaranAman,DelhiDelhiDelhiDelhi,4,206000,2024-01-052024-01-102024-01-152024-01-22
Mouse,316,AmanNehaRiya,MumbaiPunePune,6,1650,2024-01-062024-01-132024-01-18

In [31]:
df.groupby("Product").agg(
    {"Quantity":"sum",
     "Price":"sum"}
).sort_values(by="Price",ascending=False)

          Quantity   Price
Product
Laptop           4  206000
Keyboard         5    4500
Mouse            6    1650

In [35]:
df.groupby("Product").agg(
    {"Price":"mean"}
).sort_values(by="Price",ascending=False)

            Price
Product
Laptop    51500.0
Keyboard   1500.0
Mouse       550.0

In [37]:
df.groupby("City").agg(
    {"OrderID":"count"}
).sort_values(by="OrderID",ascending=False)

        OrderID
City
Delhi         5
Mumbai        3
Pune          2

In [45]:
df.groupby("Product").agg(
    Quantity = ("Quantity","sum"),
     Count = ("Product","count")
).sort_values(by="Quantity",ascending=False)

          Quantity  Count
Product
Mouse            6      3
Keyboard         5      3
Laptop           4      4

In [ ]:
df[]